name: Manual Publish Package
run-name: Version ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'The version to publish. Must be a valid semver version. i.e. 1.0.0-beta.1'
jobs:
  manual-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install
        run: npm ci
      - name: Set version
        run: npm version ${{ inputs.version }} --no-git-tag-version
      - name: Release
        run: npm publish --access public --tag beta
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}